### ISSUE TITLE
Accessing MS Trending data

### ISSUE THREAD

**Issue by heejongkim** [thermofisherlsms/RawFileReader#14]
Hello,

Thanks for providing this fantastic interface. This truly transformed the way I work with MS data.
While I'm still reading and learning, one thing came up and I just can't have a clue of it so it would be awesome if I can get some hints from you guys.

I've been trying to access MS trending (given that FreeStyle indicates a separate device) by testing MS, MSAnalog, and Other to get extra info but it seems I'm missing an important piece or misunderstanding about it.

Can you please help by providing some minimal python or C# snippets how to get into that?

Thank you so much.

best,
heejong

**Comment by jesse-canterbury** [comment]
Hi Heejong, it's great that you're getting good use out of these tools.

In lieu of a more "official" response, about whether the MS Trending info is available directly, note that the MS Trending info is, I believe, a plot vs retention time of various parameters included in the raw file for each spectrum.  You should be able to find the parameter(s) you're looking for either in the "trailer extra" or the "status log," and then extract your favorite item for each spectrum.  In the Program.cs file for RawFileReader, take a look at the ListTrailerExtraFields and ListStatusLog functions.  Those should give you some info about what's available & will hopefully help get you started.

**Comment by heejongkim** [comment]
Hi Jesse,

Thank you so much for the explanation.
It seems "trailer extra" has all those information that we usually check for the quality of data (e.g. AGC, IT, isolation width, HCD energy, Lock mass, APD, etc) while "status log" has a lot more mechanical details (Spray voltage/current, flatapole info, temperature of each parts, and so forth). I'm amazed how much details the raw file has.
Now I have a multi y-axes line plot for spray voltage and current across RT!
Thank you!

best,
heejong
